# Generated by Django 5.1.3 on 2024-12-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_customersegment_customernote_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="parameters",
        ),
        migrations.AddField(
            model_name="report",
            name="assignee_filter",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="report",
            name="category_filter",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="report",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="group_by",
            field=models.CharField(
                choices=[
                    ("day", "Daily"),
                    ("week", "Weekly"),
                    ("month", "Monthly"),
                    ("quarter", "Quarterly"),
                    ("year", "Yearly"),
                ],
                default="month",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="include_inactive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="max_items",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="report",
            name="min_interactions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="status_filter",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
